import '../../../core/api/api_error_mapper.dart';
import '../../../core/api/api_failure.dart';
import '../../../core/api/generated/clients/campaigns_api.dart';
import '../../../core/api/generated/clients/users_api.dart';
import '../../../core/api/generated/models/campaign_member_add.dart';
import '../../../core/api/generated/models/campaign_member_out.dart';
import '../../../core/api/generated/models/user_invite.dart';
import '../../../core/api/generated/models/user_out.dart';
import '../../../core/i18n/generated/app_localizations.dart';

/// How a centre role reads.
String centerRoleLabel(AppLocalizations l10n, String? role) => switch (role) {
  'volunteer' => l10n.roleVolunteerLabel,
  'coordinator' => l10n.roleCoordinatorLabel,
  'national_admin' => l10n.roleNationalAdminLabel,
  null => l10n.roleNone,
  _ => role,
};

/// How an operation on the team ended.
/// What can be said to somebody who has just changed something about the team.
enum TeamNotice { invited, accessResent }

sealed class TeamOutcome {
  const TeamOutcome();
}

final class TeamChanged extends TeamOutcome {
  const TeamChanged({this.notice});

  /// What happened, when there is something to say. It is a marker and not a
  /// sentence: the data layer does not know which language is being read.

  /// What has to be told to whoever asked for it, when there is something to
  /// tell: inviting and reinviting send an email, and that is not visible from
  /// here.
  final TeamNotice? notice;
}

final class TeamRefused extends TeamOutcome {
  const TeamRefused(this.failure);

  final ApiFailure failure;

  /// The failure, not a sentence: wording it here would pick a language in a
  /// layer that does not know which one is being read.
  ApiFailure get reason => failure;
}

/// The centre's team and who takes part in each campaign.
///
/// All of this is online and decided by the server: whoever coordinates only
/// sees and touches people from their own centre, and the backend checks that
/// on every call. That rule is not replicated here; all that is avoided is
/// offering what is going to fail.
class TeamRepository {
  TeamRepository({required CampaignsApi campaigns, required UsersApi users})
    : _campaignsApi = campaigns,
      _usersApi = users;

  final CampaignsApi _campaignsApi;
  final UsersApi _usersApi;

  Future<List<UserOut>> centerUsers(String centerId) =>
      _usersApi.listCenterUsersV1CentersCenterIdUsersGet(centerId: centerId);

  Future<List<CampaignMemberOut>> members(String campaignId) => _campaignsApi
      .listMembersV1CampaignsCampaignIdMembersGet(campaignId: campaignId);

  Future<TeamOutcome> addMember({
    required String campaignId,
    required String userId,
  }) => _attempt(
    () => _campaignsApi.addMemberV1CampaignsCampaignIdMembersPost(
      campaignId: campaignId,
      body: CampaignMemberAdd(userId: userId),
    ),
  );

  Future<TeamOutcome> removeMember({
    required String campaignId,
    required String userId,
  }) => _attempt(
    () => _campaignsApi.removeMemberV1CampaignsCampaignIdMembersUserIdDelete(
      campaignId: campaignId,
      userId: userId,
    ),
  );

  /// Adds somebody at the centre.
  ///
  /// The password is generated by the server and travels by email: from here it
  /// is neither seen nor chosen, and that is why the notice says to wait for
  /// that email.
  Future<TeamOutcome> invite({
    required String centerId,
    required String email,
    required String username,
    String? fullName,
    required String centerRole,
  }) => _attempt(
    () => _usersApi.inviteUserV1CentersCenterIdUsersPost(
      centerId: centerId,
      body: UserInvite(
        email: email,
        username: username,
        fullName: fullName,
        centerRole: centerRole,
      ),
    ),
    notice: TeamNotice.invited,
  );

  /// Sends the access again. The previous password stops working.
  Future<TeamOutcome> reinvite({
    required String centerId,
    required String userId,
  }) => _attempt(
    () => _usersApi.reinviteCenterUserV1CentersCenterIdUsersUserIdReinvitePost(
      centerId: centerId,
      userId: userId,
    ),
    notice: TeamNotice.accessResent,
  );

  Future<TeamOutcome> _attempt(
    Future<void> Function() call, {
    TeamNotice? notice,
  }) async {
    try {
      await call();
      return TeamChanged(notice: notice);
    } on Object catch (error) {
      return TeamRefused(ApiErrorMapper.fromAny(error));
    }
  }
}
