import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/api/api_error_mapper.dart';
import '../../../core/auth/auth_providers.dart';
import '../../../core/i18n/l10n_extension.dart';
import 'login_view.dart';

/// Changing the password, whether required or chosen.
///
/// It is the same form in both cases because it is the same operation; the only
/// thing that changes is why somebody is here.
///
/// With [forced] the backend marked `must_change_password`: the key was
/// generated by whoever administers when creating or resetting the account, and
/// the screen stands in the way before operating with no way around it, because
/// its reason to exist is that a temporary key sent by email stops working as
/// soon as it is used.
///
/// Without [forced] it is reached from the profile, because nobody should have
/// to wait to be forced before changing a password they believe compromised.
class ChangePasswordView extends ConsumerStatefulWidget {
  const ChangePasswordView({super.key, this.forced = true});

  final bool forced;

  @override
  ConsumerState<ChangePasswordView> createState() => _ChangePasswordViewState();
}

class _ChangePasswordViewState extends ConsumerState<ChangePasswordView> {
  final _formKey = GlobalKey<FormState>();
  final _current = TextEditingController();
  final _next = TextEditingController();
  final _confirm = TextEditingController();
  bool _submitting = false;
  String? _failure;

  @override
  void dispose() {
    _current.dispose();
    _next.dispose();
    _confirm.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!(_formKey.currentState?.validate() ?? false)) return;

    setState(() {
      _submitting = true;
      _failure = null;
    });

    try {
      await ref
          .read(sessionControllerProvider.notifier)
          .changePassword(
            currentPassword: _current.text,
            newPassword: _next.text,
          );
      // In the required case there is nowhere to go back to: the session's gate
      // stops interposing this screen by itself. In the voluntary one there is,
      // and staying here saying nothing would look as though nothing happened.
      if (!widget.forced && mounted) {
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context)
          ..hideCurrentSnackBar()
          ..showSnackBar(SnackBar(content: Text(context.l10n.passwordUpdated)));
      }
    } on Object catch (error) {
      // The password policy is defined and applied by the server; its message
      // is the one shown.
      if (mounted) {
        setState(
          () => _failure = ApiErrorMapper.fromAny(
            error,
          ).operatorMessage(context.l10n),
        );
      }
    } finally {
      if (mounted) setState(() => _submitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(context.l10n.changePasswordTitle),
        automaticallyImplyLeading: !widget.forced,
      ),
      body: SafeArea(
        child: Center(
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 420),
              child: Form(
                key: _formKey,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Text(
                      widget.forced
                          ? context.l10n.forcedPasswordChangeExplanation
                          : context.l10n.deliberatePasswordChangeExplanation,
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                    const SizedBox(height: 24),
                    TextFormField(
                      controller: _current,
                      obscureText: true,
                      decoration: InputDecoration(
                        labelText: context.l10n.currentPasswordLabel,
                      ),
                      validator: (value) => (value == null || value.isEmpty)
                          ? context.l10n.currentPasswordRequired
                          : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _next,
                      obscureText: true,
                      decoration: InputDecoration(
                        labelText: context.l10n.newPasswordLabel,
                      ),
                      validator: (value) => (value == null || value.isEmpty)
                          ? context.l10n.newPasswordRequired
                          : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _confirm,
                      obscureText: true,
                      onFieldSubmitted: (_) => _submit(),
                      decoration: InputDecoration(
                        labelText: context.l10n.repeatNewPasswordLabel,
                      ),
                      // The only thing validated here: that the two match. It
                      // is a slip of the finger the server cannot detect.
                      validator: (value) => value != _next.text
                          ? context.l10n.passwordsDoNotMatch
                          : null,
                    ),
                    if (_failure case final message?) ...[
                      const SizedBox(height: 16),
                      SessionFailureBanner(message: message),
                    ],
                    const SizedBox(height: 24),
                    FilledButton(
                      onPressed: _submitting ? null : _submit,
                      child: _submitting
                          ? const SizedBox.square(
                              dimension: 20,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            )
                          : Text(
                              widget.forced
                                  ? context.l10n.actionSaveAndContinue
                                  : context.l10n.actionSave,
                            ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
